[package]
name = "jrsonnet-fmt"
version.workspace = true
edition = "2021"

[dependencies]
dprint-core.workspace = true
jrsonnet-rowan-parser.workspace = true
insta.workspace = true
indoc.workspace = true
ass-stroke.workspace = true
clap = { workspace = true, features = ["derive"] }
tempfile.workspace = true
thiserror.workspace = true
