[package]
name = "jrsonnet-fmt"
version.workspace = true
edition = "2021"

[dependencies]
dprint-core = "0.63.2"
jrsonnet-rowan-parser.workspace = true
insta = "1.15"
indoc = "1.0"
ass-stroke = { path = "/home/lach/build/ass-stroke/crates/ass-stroke", version = "0.1.0" }
clap = { version = "4.4.2", features = ["derive"] }
tempfile = "3.8.0"
thiserror = "1.0.48"
