[workspace]
members = [
	"crates/jsonnet-parser",
	"crates/jsonnet-evaluator",
	"crates/jsonnet-stdlib",
	"cmds/jsonnet"
]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
debug = 0
panic = "abort"
