[workspace]
members = [
	"crates/jrsonnet-parser",
	"crates/jrsonnet-evaluator",
	"crates/jrsonnet-stdlib",
	"bindings/jsonnet",
	"cmds/jrsonnet"
]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
debug = 0
panic = "abort"
