[package]
name = "jrsonnet"
description = "Rust jsonnet implementation"
version = "0.3.1"
authors = ["Лач <iam@lach.pw>"]
license = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
# Use mimalloc as allocator
mimalloc = []

[dependencies]
jrsonnet-evaluator = { path = "../../crates/jrsonnet-evaluator", version = "0.3.1" }
jrsonnet-parser = { path = "../../crates/jrsonnet-parser", version = "0.3.1" }
jrsonnet-cli = { path = "../../crates/jrsonnet-cli", version = "0.3.1" }
# TODO: Fix mimalloc compile errors, and use them
mimallocator = { version = "0.1.3", optional = true }
thiserror = "1.0.21"

[dependencies.clap]
git = "https://github.com/clap-rs/clap"
rev = "3e9ee86713b5c407b50ba76f30cffaed25952063"
