[package]
name = "jrsonnet"
description = "Rust jsonnet implementation"
version = "0.3.4"
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
license = "MIT"
edition = "2018"

[features]
default = []
# Use mimalloc as allocator
mimalloc = []

[dependencies]
jrsonnet-evaluator = { path = "../../crates/jrsonnet-evaluator", version = "0.3.4" }
jrsonnet-parser = { path = "../../crates/jrsonnet-parser", version = "0.3.4" }
jrsonnet-cli = { path = "../../crates/jrsonnet-cli", version = "0.3.4" }
# TODO: Fix mimalloc compile errors, and use them
mimallocator = { version = "0.1.3", optional = true }
thiserror = "1.0"

[dependencies.clap]
git = "https://github.com/clap-rs/clap"
rev = "50fb4ca63dc7e8fb8aa2914de5c8a5b4413f2c62"
