[package]
name = "jrsonnet"
description = "Rust jsonnet implementation"
version = "0.4.1"
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
license = "MIT"
edition = "2018"
publish = false

[features]
# Use mimalloc as allocator
mimalloc = ["mimallocator"]

[dependencies]
jrsonnet-evaluator = { path="../../crates/jrsonnet-evaluator", version="0.4.1" }
jrsonnet-parser = { path="../../crates/jrsonnet-parser", version="0.4.1" }
jrsonnet-cli = { path="../../crates/jrsonnet-cli", version="0.4.1" }
mimallocator = { version="0.1.3", optional=true }
thiserror = "1.0"

[dependencies.clap]
git = "https://github.com/clap-rs/clap"
rev = "f0c5ea5e1503de5c8e74d8c047a799cf51498e83"

[dependencies.clap_generate]
git = "https://github.com/clap-rs/clap"
rev = "f0c5ea5e1503de5c8e74d8c047a799cf51498e83"
