[package]
name = "jrsonnet"
description = "Rust jsonnet implementation"
version = "1.0.0"
authors = ["Лач <iam@lach.pw>"]
license = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jrsonnet-evaluator = { path = "../../crates/jrsonnet-evaluator", version = "1.0.0" }
jrsonnet-parser = { path = "../../crates/jrsonnet-parser", version = "1.0.0" }
annotate-snippets = "0.8.0"
jemallocator = "0.3.2"

[dependencies.clap]
version = "3.0.0-beta.1"
default-features = false
features = ["std", "derive"]
