[package]
name = "jrsonnet"
version = "0.1.0"
authors = ["Лач <iam@lach.pw>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jrsonnet-evaluator = { path = "../../crates/jrsonnet-evaluator" }
jrsonnet-parser = { path = "../../crates/jrsonnet-parser" }
annotate-snippets = "0.8.0"
jemallocator = "0.3.2"

[dependencies.clap]
version = "3.0.0-beta.1"
default-features = false
features = ["std", "derive"]
