[package]
name = "jrsonnet"
description = "Rust jsonnet implementation"
version = "0.3.8"
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
license = "MIT"
edition = "2018"
publish = false

[features]
default = []
# Use mimalloc as allocator
mimalloc = []

[dependencies]
jrsonnet-evaluator = { path = "../../crates/jrsonnet-evaluator", version = "0.3.8" }
jrsonnet-parser = { path = "../../crates/jrsonnet-parser", version = "0.3.8" }
jrsonnet-cli = { path = "../../crates/jrsonnet-cli", version = "0.3.8" }
# TODO: Fix mimalloc compile errors, and use them
mimallocator = { version = "0.1.3", optional = true }
thiserror = "1.0"

[dependencies.clap]
git = "https://github.com/clap-rs/clap"
rev = "92f744cc49d12d32261010d355dc215a6d2487b9"

[dependencies.clap_generate]
git = "https://github.com/clap-rs/clap"
rev = "92f744cc49d12d32261010d355dc215a6d2487b9"
