[package]
name = "jrsonnet"
description = "Rust jsonnet implementation"
version = "0.3.6"
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
license = "MIT"
edition = "2018"

[features]
default = []
# Use mimalloc as allocator
mimalloc = []

[dependencies]
jrsonnet-evaluator = { path = "../../crates/jrsonnet-evaluator", version = "0.3.6" }
jrsonnet-parser = { path = "../../crates/jrsonnet-parser", version = "0.3.6" }
jrsonnet-cli = { path = "../../crates/jrsonnet-cli", version = "0.3.6" }
# TODO: Fix mimalloc compile errors, and use them
mimallocator = { version = "0.1.3", optional = true }
thiserror = "1.0"
clap = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.2"
