[package]
name = "jrsonnet"
description = "Rust jsonnet implementation"
version = "0.3.0"
authors = ["Лач <iam@lach.pw>"]
license = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
# Use mimalloc as allocator
mimalloc = []

[dependencies]
jrsonnet-evaluator = { path = "../../crates/jrsonnet-evaluator", version = "0.3.0" }
jrsonnet-parser = { path = "../../crates/jrsonnet-parser", version = "0.3.0" }
jrsonnet-cli = { path = "../../crates/jrsonnet-cli", version = "0.1.0" }
# TODO: Fix mimalloc compile errors, and use them
mimallocator = { version = "0.1.3", optional = true }

[dependencies.clap]
git = "https://github.com/clap-rs/clap"
rev = "6a56a82629d1a990efb37dae9c75a76e943f22a0"
