[package]
name = "jrsonnet-types"
description = "Jrsonnet type system definition"
version.workspace = true
repository.workspace = true
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
license = "MIT"
edition = "2021"

[dependencies]
jrsonnet-gcmodule.workspace = true

peg = "0.8.1"
