[package]
name = "jrsonnet-types"
description = "Jrsonnet type system definition"
version = "0.3.7"
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
license = "MIT"
edition = "2018"

[dependencies]
peg = "0.7.0"
