[package]
name = "jrsonnet-parser"
description = "jsonnet language parser and AST"
version = "1.0.0"
authors = ["Лач <iam@lach.pw>"]
license = "MIT"
edition = "2018"

[features]
default = []
serialize = ["serde"]
deserialize = ["serde"]
# Adds ability to dump AST as source code for easy embedding
dump = ["structdump", "structdump-derive"]

[dependencies]
peg = "0.6.2"
unescape = "0.1.0"

serde = { version = "1.0.114", features = ["derive", "rc"], optional = true }
structdump = { version = "0.1.2", optional = true }
structdump-derive = { version = "0.1.2", optional = true }

[dev-dependencies]
jrsonnet-stdlib = { path = "../jrsonnet-stdlib", version = "1.0.0" }
