[package]
name = "jrsonnet-parser"
description = "jsonnet language parser and AST"
version = "0.4.0"
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
license = "MIT"
edition = "2018"

[features]
default = []
serialize = ["serde"]
deserialize = ["serde"]

[dependencies]
jrsonnet-interner = { path = "../jrsonnet-interner", version = "0.4.0" }

peg = "0.7.0"
unescape = "0.1.0"

serde = { version = "1.0", features = ["derive", "rc"], optional = true }
jrsonnet-gc = { version = "0.4.2", features = ["derive"] }

[dev-dependencies]
jrsonnet-stdlib = { path = "../jrsonnet-stdlib", version = "0.4.0" }
