[package]
name = "jrsonnet-parser"
description = "jsonnet language parser and AST"
version = "0.4.2"
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
license = "MIT"
edition = "2021"

[dependencies]
jrsonnet-interner = { path = "../jrsonnet-interner", version = "0.4.2" }

peg = "0.8.0"

serde = { version = "1.0", features = ["derive", "rc"], optional = true }
gcmodule = { git = "https://github.com/CertainLach/gcmodule", branch = "jrsonnet" }

[dev-dependencies]
jrsonnet-stdlib = { path = "../jrsonnet-stdlib", version = "0.4.2" }
