[package]
name = "jsonnet-parser"
version = "0.1.0"
authors = ["Лач <iam@lach.pw>"]
edition = "2018"

[features]
default = []
# Trace peg token parsing
trace = ["peg/trace"]

[dependencies]
peg = "0.6.2"
