[package]
name = "jrsonnet-lsp"
version.workspace = true
edition = "2021"

[dependencies]
anyhow.workspace = true
jrsonnet-evaluator.workspace = true
jrsonnet-rowan-parser.workspace = true
lsp-server.workspace = true
lsp-types.workspace = true
serde.workspace = true
serde_json.workspace = true
