[package]
name = "jrsonnet-stdlib"
description = "jsonnet standard library packaged as crate"
version.workspace = true
repository.workspace = true
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
license = "MIT"
edition = "2021"

[features]
default = ["codegenerated-stdlib"]
# Speed-up initialization by generating code for parsed stdlib, instead
# of invoking parser for it
codegenerated-stdlib = ["jrsonnet-parser/structdump"]
# Enables legacy `std.thisFile` support, at the cost of worse caching
legacy-this-file = []
# Add order preservation flag to some functions
exp-preserve-order = ["jrsonnet-evaluator/exp-preserve-order"]
# Add nonstandard `std.sha256` function
exp-more-hashes = ["dep:sha2"]
# Bigint type
exp-bigint = ["num-bigint", "jrsonnet-evaluator/exp-bigint"]

[dependencies]
jrsonnet-evaluator.workspace = true
jrsonnet-macros.workspace = true
jrsonnet-parser.workspace = true
jrsonnet-gcmodule.workspace = true

# Used for stdlib AST serialization
bincode = { version = "1.3", optional = true }
# Used both for stdlib AST serialization and std.parseJson/std.parseYaml
serde = "1.0"

# std.md5
md5 = "0.7.0"
# std.base64
base64 = "0.21.0"
# std.parseJson
serde_json = "1.0"
# std.parseYaml, custom library fork is used for C++/golang compatibility
serde_yaml_with_quirks = "0.8.24"

sha2 = { version = "0.10.6", optional = true }
num-bigint = { version = "0.4.3", optional = true }

[build-dependencies]
jrsonnet-parser.workspace = true
structdump = { version = "0.2.0", features = ["derive"] }
