[package]
name = "jrsonnet-stdlib"
description = "jsonnet standard library packaged as crate"
version = "0.3.4"
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
license = "MIT"
edition = "2018"

[features]

[dependencies]
