[package]
name = "jrsonnet-evaluator"
description = "jsonnet interpreter"
version = "0.4.2"
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
license = "MIT"
edition = "2021"

[features]
default = ["serialized-stdlib", "explaining-traces"]
# Serializes standard library AST instead of parsing them every run
serialized-stdlib = ["bincode", "jrsonnet-parser/deserialize"]
# Rustc-like trace visualization
explaining-traces = ["annotate-snippets"]
# Allows library authors to throw custom errors
anyhow-error = ["anyhow"]

[dependencies]
jrsonnet-interner = { path = "../jrsonnet-interner", version = "0.4.2" }
jrsonnet-parser = { path = "../jrsonnet-parser", version = "0.4.2" }
jrsonnet-stdlib = { path = "../jrsonnet-stdlib", version = "0.4.2" }
jrsonnet-types = { path = "../jrsonnet-types", version = "0.4.2" }
jrsonnet-macros = { path = "../jrsonnet-macros", version = "0.4.2" }
pathdiff = "0.2.0"

md5 = "0.7.0"
base64 = "0.13.0"
rustc-hash = "1.1.0"

thiserror = "1.0"
gcmodule = { git = "https://github.com/CertainLach/gcmodule", branch = "jrsonnet" }

serde = "1.0"
serde_json = "1.0"
serde_yaml = { git = "https://github.com/CertainLach/serde-yaml", branch = "feature/old-octals-quirk" }

[dependencies.anyhow]
version = "1.0"
optional = true

# Serialized stdlib
[dependencies.bincode]
version = "1.3.1"
optional = true

# Explaining traces
[dependencies.annotate-snippets]
version = "0.9.1"
features = ["color"]
optional = true

[build-dependencies]
jrsonnet-parser = { path = "../jrsonnet-parser", features = [
    "serialize",
    "deserialize",
], version = "0.4.2" }
jrsonnet-stdlib = { path = "../jrsonnet-stdlib", version = "0.4.2" }
serde = "1.0"
bincode = "1.3.1"
