[package]
name = "jrsonnet-evaluator"
description = "jsonnet interpreter"
version = "1.0.0"
authors = ["Лач <iam@lach.pw>"]
license = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["serialized-stdlib", "faster"]
# Serializes standard library AST instead of parsing them every run
serialized-stdlib = ["serde", "bincode", "jrsonnet-parser/deserialize"]
# Same as above, but with generated code instead of serde. Reduces memory usage, but increases binary size and compilation time
codegenerated-stdlib = []
# Replace some standard library functions with faster implementations (I.e manifestJsonEx)
# Library works fine without this feature, but requires more memory and time for std function calls
faster = []

[dependencies]
jrsonnet-parser = { path = "../jrsonnet-parser", version = "1.0.0" }
closure = "0.3.0"
jrsonnet-stdlib = { path = "../jrsonnet-stdlib", version = "1.0.0" }
indexmap = "1.4.0"
md5 = "0.7.0"

serde = { version = "1.0.114", optional = true }
bincode = { version = "1.3.1", optional = true }

[build-dependencies]
jrsonnet-parser = { path = "../jrsonnet-parser", features = ["dump", "serialize", "deserialize"], version = "1.0.0" }
jrsonnet-stdlib = { path = "../jrsonnet-stdlib", version = "1.0.0" }
structdump = "0.1.2"
serde = "1.0.114"
bincode = "1.3.1"
