[package]
name = "jrsonnet-evaluator"
description = "jsonnet interpreter"
version = "0.4.1"
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
license = "MIT"
edition = "2018"

[features]
default = ["serialized-stdlib", "explaining-traces", "serde-json"]
# Serializes standard library AST instead of parsing them every run
serialized-stdlib = ["serde", "bincode", "jrsonnet-parser/deserialize"]
# Allow to convert Val into serde_json::Value and backwards
serde-json = ["serde", "serde_json"]
# Rustc-like trace visualization
explaining-traces = ["annotate-snippets"]
# Allows library authors to throw custom errors
anyhow-error = ["anyhow"]

# Unlocks extra features, but works only on unstable
unstable = []

[dependencies]
jrsonnet-interner = { path="../jrsonnet-interner", version="0.4.1" }
jrsonnet-parser = { path="../jrsonnet-parser", version="0.4.1" }
jrsonnet-stdlib = { path="../jrsonnet-stdlib", version="0.4.1" }
jrsonnet-types = { path="../jrsonnet-types", version="0.4.1" }
pathdiff = "0.2.0"

md5 = "0.7.0"
base64 = "0.13.0"
rustc-hash = "1.1.0"

thiserror = "1.0"
jrsonnet-gc = { version="0.4.2", features=["derive"] }

[dependencies.anyhow]
version = "1.0"
optional = true

# Serialized stdlib
[dependencies.serde]
version = "1.0"
optional = true
[dependencies.bincode]
version = "1.3.1"
optional = true

# Serde json
[dependencies.serde_json]
version = "1.0"
optional = true

# Explaining traces
[dependencies.annotate-snippets]
version = "0.9.0"
features = ["color"]
optional = true

[build-dependencies]
jrsonnet-parser = { path="../jrsonnet-parser", features=["serialize", "deserialize"], version="0.4.1" }
jrsonnet-stdlib = { path="../jrsonnet-stdlib", version="0.4.1" }
serde = "1.0"
bincode = "1.3.1"
