[package]
name = "jrsonnet-macros"
version = "0.4.2"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.32"
quote = "1.0.10"
syn = { version = "1.0.82", features = ["full"] }
