[package]
name = "jrsonnet-cli"
description = "Utilities for building jrsonnet CLIs"
version = "0.3.2"
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
edition = "2018"

[dependencies]
jrsonnet-evaluator = { path = "../../crates/jrsonnet-evaluator", version = "0.3.2", features = ["explaining-traces"] }
jrsonnet-parser = { path = "../../crates/jrsonnet-parser", version = "0.3.2" }

[dependencies.clap]
git = "https://github.com/clap-rs/clap"
rev = "50fb4ca63dc7e8fb8aa2914de5c8a5b4413f2c62"
