[package]
name = "jrsonnet-cli"
description = "Utilities for building jrsonnet CLIs"
version = "0.1.0"
authors = ["Лач <iam@lach.pw>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jrsonnet-evaluator = { path = "../../crates/jrsonnet-evaluator", version = "0.3.0", features = ["explaining-traces"] }
jrsonnet-parser = { path = "../../crates/jrsonnet-parser", version = "0.3.0" }

[dependencies.clap]
git = "https://github.com/clap-rs/clap"
rev = "6a56a82629d1a990efb37dae9c75a76e943f22a0"
