[package]
name = "location-formatter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smallvec = "1.10.0"
range-map = "0.2.0"
random_color = "0.6.1"
rand = "0.8.5"
num-traits = "0.2.15"
