[package]
name = "jsonnet"
version = "0.3.4"
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
edition = "2018"

[dependencies]
jrsonnet-interner = { path = "../../crates/jrsonnet-interner", version = "0.3.4" }
jrsonnet-evaluator = { path = "../../crates/jrsonnet-evaluator", version = "0.3.4" }
jrsonnet-parser = { path = "../../crates/jrsonnet-parser", version = "0.3.4" }

[lib]
crate-type = ["cdylib"]
