[package]
name = "jsonnet"
description = "Rust implementation of libjsonnet.so"
version = "0.3.8"
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
license = "MIT"
edition = "2018"
publish = false

[dependencies]
jrsonnet-interner = { path = "../../crates/jrsonnet-interner", version = "0.3.8" }
jrsonnet-evaluator = { path = "../../crates/jrsonnet-evaluator", version = "0.3.8" }
jrsonnet-parser = { path = "../../crates/jrsonnet-parser", version = "0.3.8" }

[lib]
crate-type = ["cdylib"]

[features]
interop = []
