[package]
name = "jsonnet"
description = "Rust implementation of libjsonnet.so"
version = "0.4.0"
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
license = "MIT"
edition = "2018"
publish = false

[dependencies]
jrsonnet-evaluator = { path = "../../crates/jrsonnet-evaluator", version = "0.4.0" }
jrsonnet-parser = { path = "../../crates/jrsonnet-parser", version = "0.4.0" }
jrsonnet-gc = { version = "0.4.2", features = ["derive"] }

[lib]
crate-type = ["cdylib"]

[features]
interop = []
