[package]
name = "jsonnet"
version = "0.3.1"
authors = ["Лач <iam@lach.pw>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jrsonnet-evaluator = { path = "../../crates/jrsonnet-evaluator", version = "0.3.1" }
jrsonnet-parser = { path = "../../crates/jrsonnet-parser", version = "0.3.1" }

[lib]
crate-type = ["cdylib"]
