[package]
name = "jsonnet"
version = "0.3.5"
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
edition = "2018"

[dependencies]
jrsonnet-interner = { path = "../../crates/jrsonnet-interner", version = "0.3.5" }
jrsonnet-evaluator = { path = "../../crates/jrsonnet-evaluator", version = "0.3.5" }
jrsonnet-parser = { path = "../../crates/jrsonnet-parser", version = "0.3.5" }

[lib]
crate-type = ["cdylib"]

[features]
interop = []
