[package]
name = "jsonnet"
version = "0.3.2"
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
edition = "2018"

[dependencies]
jrsonnet-evaluator = { path = "../../crates/jrsonnet-evaluator", version = "0.3.2" }
jrsonnet-parser = { path = "../../crates/jrsonnet-parser", version = "0.3.2" }

[lib]
crate-type = ["cdylib"]
