[package]
name = "jrsonnet-interner"
description = "Jrsonnet string interning"
version.workspace = true
repository.workspace = true
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
license = "MIT"
edition = "2021"

[features]
default = []
# Implement value serialization using structdump
structdump = ["dep:structdump"]
# Implement value serialization using serde
#
# Warning: serialized values won't be deduplicated
serde = ["dep:serde"]

[dependencies]

serde = { workspace = true, optional = true }
structdump = { workspace = true, optional = true }

rustc-hash.workspace = true
hashbrown = { workspace = true, features = ["inline-more"] }
boa_gc = { git = "https://github.com/boa-dev/boa", version = "0.17.0" }
