[package]
name = "jrsonnet-interner"
description = "Jrsonnet string interning"
version = "0.3.6"
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
edition = "2018"

[dependencies]
serde = { version = "1.0" }
rustc-hash = "1.1.0"
