[package]
name = "jrsonnet-interner"
description = "Jrsonnet string interning"
version = "0.4.2"
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
license = "MIT"
edition = "2018"

[dependencies]
serde = { version = "1.0" }
rustc-hash = "1.1.0"
gcmodule = { git = "https://github.com/CertainLach/gcmodule", branch = "jrsonnet" }
